### ISSUE TITLE
More than 20? Aka Load More Button

### ISSUE THREAD

**Issue by ustincameron** [sounden/phinstagram#1]
Is this possible with PHP in any way at all? I appreciate your work, I'm also writing a minimal scraper, but can only get 15 or so photos.

**Comment by sounden** [comment]
As for now it only works with the initial images as shown on the profile since that is included in the body of the HTML. To be able to load more images you need to have some JavaScript enabled scraper. Maybe it works in some other way as well, I have not put anymore effort into it. 

One way to would be to rewrite the cache logic to store all images permanently.

Maybe I will look into it later
